name: Desplegar ERP a Testing

on:
  push:
    branches:
      - desarrollo

jobs:
  web-deploy:
    name: Despliegue vía FTP
    runs-on: ubuntu-latest
    steps:
    - name: Obtener última versión del código
      uses: actions/checkout@v4
    
    - name: Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./
        port: 21
        security: loose
